# Setup a simple meteor webapp
# You can build the docker image with:
#   $ docker build -t yourname/app .
# Then you can run your meteor image with
#
# $  docker run -d \
#        -e ROOT_URL=http://yourapp.com \
#        -e MONGO_URL=mongodb://url \
#        -e MONGO_OPLOG_URL=mongodb://oplog_url \
#        -p 8080:80 \
#        yourname/app

FROM meteorhacks/meteord:onbuild

MAINTAINER Pierre-Elouan Rethore <pire@dtu.dk>
